name: Build MoonTVc image

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build moonTV image
    runs-on: ubuntu-latest
    if: (github.event.workflow_run.conclusion == 'success' && github.repository == 'ooroot/MoonTVc') || (github.repository == 'ooroot/MoonTVc')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Read version from VERSION.txt
        id: version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
- name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # set latest tag for master branch
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MoonTVc image
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.set-tag.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7